### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by BlazyDoesDev** [Yariya/EarnApp-Earning-Monitor#13]
https://gist.github.com/BlazyDoesDev/42c1ebbdf5b90303e8c69a803f6cd454
It worked before for a bit.

**Comment by BlazyDoesDev** [comment]
Seems like it was wrong token. Maybe a neater error message would be good?

**Comment by Yariya** [comment]
yes :)

**Comment by fazalfarhan01** [comment]
> Seems like it was wrong token. Maybe a neater error message would be good?

The code base is now completely changed.
FIXED
