### ISSUE TITLE
Traffic in negative range

### ISSUE THREAD

**Issue by Yariya** [Yariya/EarnApp-Earning-Monitor#27]
![Screenshot_87](https://user-images.githubusercontent.com/65712074/142733083-d4ba8883-3b47-4250-90e6-fd62390ab1d8.jpg)
![Screenshot_88](https://user-images.githubusercontent.com/65712074/142733092-595395bf-67d3-40f5-aceb-216dd88b8005.jpg)

**Comment by fazalfarhan01** [comment]
Updated to the latest version? I fixed it in the last release.

**Comment by Yariya** [comment]
Alright thanks :) will forward it

**Comment by fazalfarhan01** [comment]
Negative balance still appears on embed right after withdrawals.

**Comment by fazalfarhan01** [comment]
Testing pending

**Comment by fazalfarhan01** [comment]
Negative balance issue has been resolved. 
But EarnApp Dashboard has some issue with showing correct balance. 
![image](https://user-images.githubusercontent.com/45929854/142796280-4fe722b0-e3bd-4a08-8c34-23d16d717f6d.png)
