### ISSUE TITLE
API JSON AttributeError?

### ISSUE THREAD

**Issue by Yariya** [Yariya/EarnApp-Earning-Monitor#28]
![Screenshot_104](https://user-images.githubusercontent.com/65712074/142868045-9b47575f-53e0-4285-92ab-734569b53b1c.jpeg)

**Comment by fazalfarhan01** [comment]
How many devices are linked?

**Comment by Yariya** [comment]
I don't know. Forwarding this from Vita

**Comment by fazalfarhan01** [comment]
This happens when some1 tries to run more than 1 instance of the application on single IP.. The server doesn't reply back with a response. 

May b earnapp has limited the request 1 ip can send in a second. Had similar issue. Thus ik. Ask if he tried running multiple instances..

**Comment by fazalfarhan01** [comment]
Found the solution.. 
Run the install.bat file once.. I had updated the pyEarnapp package.. 0.0.7 is the latest and that should get installed.
