### ISSUE TITLE
This for macOS?

### ISSUE THREAD

**Issue by Cayden2606** [Yariya/EarnApp-Earning-Monitor#29]
Hi idk how to run this on mac can anyone help pls.

**Comment by Yariya** [comment]
Hello, yes this can be executed on mac. It is a little more difficult than setting it up on Windows but it works!

I will make an tutorial soon

**Comment by Yariya** [comment]
It should be nearly the same as linux installation tho.

Try this: https://github.com/Yariya/EarnApp-Earning-Monitor#linux-installation

**Comment by fazalfarhan01** [comment]
> It should be nearly the same as linux installation tho.
> 
> Try this: https://github.com/Yariya/EarnApp-Earning-Monitor#linux-installation

It's exactly like Linux, except for the last 2 steps.
Install python
Then run the following commands
```SH
python3 -m pip install --upgrade -r requirements.txt
python3 app/main.py
```
