### ISSUE TITLE
python error 'last name'

### ISSUE THREAD

**Issue by XcPlease** [Yariya/EarnApp-Earning-Monitor#30]
self.last_name = json_user_data["last_name"]
KeyError: 'last_name' 

any help?

**Comment by fazalfarhan01** [comment]
What OS are you on and what version of this software are you using?

**Comment by Yariya** [comment]
Might be an problem from your google auth

**Comment by MrAuronTV** [comment]
> ```
> self.last_name = json_user_data["last_name"]
> ```
> 
> KeyError: 'last_name'
> 
> any help?

Hello i have the same issue and i solved it, you doesnt have last name on your google account, check on it, and delete your cookie and relog on earnapp with your google account, and get your auth refresh token, it works for me

**Comment by fazalfarhan01** [comment]
> 

@MrAuronTV Do you mean the error is shown for people who don't have a last name setup in google account?
So you set your last name on google and it worked?

**Comment by MrAuronTV** [comment]
@fazalfarhan01 Yep it work for me, just recreate cookie for a new oauth refresh token

**Comment by kouranio** [comment]
hello, i tried to remove this line and after starting the start.sh it worked, so i guess it's not really needed

**Comment by fazalfarhan01** [comment]
@kouranio Will be fixed in the next update.

**Comment by fazalfarhan01** [comment]
fixed is the [new release](https://github.com/Yariya/EarnApp-Earning-Monitor/releases/tag/v2.1.7.2)
