### ISSUE TITLE
windows autostart

### ISSUE THREAD

**Issue by nowaczuk** [Yariya/EarnApp-Earning-Monitor#33]
is there any way to autostart the bot on windows, without typing yes on start, for use existing configuration?

**Comment by fazalfarhan01** [comment]
Yep. You'll have to set the following 2 environment variables.

1. WEBHOOK_URL
2. AUTH
(Make sure they are all capitalised)

Follow [this guide](https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0) to set it up

**Comment by nowaczuk** [comment]
this does not work.....
when i now write no, it use the system variables, but i have to write no or yes when the bot starts
so i cant set the bot to autostart :(

**Comment by fazalfarhan01** [comment]
The exact same code is used to build the docker containers. The code first tries to grab the values from the environment variables, if it doesn't find them, it then asks you for the input. 

As long as the environment variables are set correctly, it will work. I have tested it myself.

You might want to logout and log back in for the environment variables to be picked up. It will work. 😄

**Comment by nowaczuk** [comment]
no, it does not work..... :(
![variablen](https://user-images.githubusercontent.com/96317309/146671413-b87ecbeb-e719-45e2-aa42-f4a68a230d2f.PNG)
and when i start the bot, it comes
![bot](https://user-images.githubusercontent.com/96317309/146671427-2872706f-710c-4ddc-a2cf-b3baba32fb08.PNG)

**Comment by fazalfarhan01** [comment]
> no, it does not work..... :( 

So here's the thing, the code first checks for the existence of a configuration file **_first_**. That means as long as the configuration file exists, it will ask you for the prompt.

Just to confirm, have you deleted the config file before running it after setting the env variables? If not, please do it by running the following command in `Powershell`. `Remove-Item $HOME\.earnapp-earning-monitor`
And to verify env variables are set correctly, please run the following commands in the `Powershell`.
1. `echo $env:AUTH`
2. `echo $env:WEBHOOK_URL`
If it outputs the correct auth and URL, plus you have deleted the file, it will work. 

Hope this helps. :)

![image](https://user-images.githubusercontent.com/45929854/146671985-8b5a2425-0b38-4610-9ba4-8d4ae17be929.png)
And as you can see, no prompt.

**Comment by nowaczuk** [comment]
yes, now it works, but the next time you start you have to do it again
the configuration will be created again ...... :(

**Comment by fazalfarhan01** [comment]
Oops.. I forgot to mention.. I implemented a fix for that in the latest release... For that you'll have to setup another env variable named `container` with value `docker`. That'll do it. :)

**Comment by nowaczuk** [comment]
yesssss, now it works, thank you very much
but how should a normal user know?
wouldn't it be better to specify the variables with parameters in the exe?
for example
EarnApp-Earning-Monitor.exe -auth "authcode" -webhook "webhook-url"

**Comment by fazalfarhan01** [comment]
> yesssss, now it works, thank you very much

You'r welcome. 

> but how should a normal user know?

It's not a feature but rather an implementation for container that happen to work for your use case 

> EarnApp-Earning-Monitor.exe -auth "authcode" -webhook "webhook-url"

That would be great. Will do it in the future updates.

**Comment by nowaczuk** [comment]
that woud be great
thanx for your work and your help :)
