### ISSUE TITLE
Bots online/offline

### ISSUE THREAD

**Issue by nestyxx** [Yariya/EarnApp-Earning-Monitor#36]
Hello.

First of all congratulations and thank you for the work done.

Is it possible to add online/offline bots in hourly updates?

You are earning with 49/49 Devices
45 onlines / 4 offlines
--

I don't know if the API can detect bots offline, but a notification as soon as a bot stops responding in order to be able to see the problem more quickly.

Thank you in advance.

**Comment by Yariya** [comment]
Hey, thanks for the feedback! This will be added in the next update.

**Comment by Yariya** [comment]
Hey, I released an early beta. Clone the project and run it via python.

**Comment by nestyxx** [comment]
Good evening. I just launched a new bot with the latest python version. Now, we will wait for the 11 p.m. update to see the changes.
No command to display the update manually?
Thank you for the super fast work :)

**Comment by nestyxx** [comment]
I launch the docker from a Synology and Docker Hub. Is the beta version available on it?

**Comment by Yariya** [comment]
Hey, alright let me know. Commands aren't possible (yet) because we use webhooks and not an bot for notifications.

**Comment by Yariya** [comment]
Not yet

**Comment by Yariya** [comment]
The entire update will be finished within few days. This was just an "rough sketch" ;)

**Comment by Yariya** [comment]
Hey, I didn't push the beta properly 3 days ago. I am very sorry for that. I will release the update most likely today!

**Comment by Yariya** [comment]
Update release: 28.02

Thanks for the idea ;)

**Comment by nestyxx** [comment]
Version 2.1.7.4 ?

**Comment by Yariya** [comment]
look releases :)

**Comment by nestyxx** [comment]
•	Added Online/Offline information about devices.
•	Added device status alert meaning if device(s) go offline you will get notified.
•	Fixxed total device calculating (remove hidden devices)
•	Gradient Banner (only for supported terminals)
❤️❤️

**Comment by nestyxx** [comment]
https://registry.hub.docker.com/r/fazalfarhan01/earnapp-earning-monitor/
Docker Hub is not update ?

**Comment by Yariya** [comment]
Hey, the docker version is not managed by me. Its managed by @fazalfarhan01

**Comment by fazalfarhan01** [comment]
> Hey, the docker version is not managed by me. Its managed by @fazalfarhan01 

Pushing the update..!
