### ISSUE TITLE
Online Devices Show zero

### ISSUE THREAD

**Issue by Yariya** [Yariya/EarnApp-Earning-Monitor#38]

**Comment by Yariya** [comment]
Api returns false on every device.

**Comment by fazalfarhan01** [comment]
> Api returns false on every device. 

Will look into it..

**Comment by Yariya** [comment]
[fixed](https://github.com/Yariya/EarnApp-Earning-Monitor/commit/2554665b826a7482963fce5e245d615c27e02acd)

**Comment by authorisation** [comment]
![image](https://user-images.githubusercontent.com/64337177/156838191-56d6b52f-1f8b-40b6-9c95-26473e9d41dd.png)

@Yariya
