### ISSUE TITLE
Suggestion for v2.2.0.3

### ISSUE THREAD

**Issue by nestyxx** [Yariya/EarnApp-Earning-Monitor#41]
Transfer to PayPal on a specific date? First day of the month by default.
Alexandre

**Comment by Yariya** [comment]
Great suggestion!

**Comment by nestyxx** [comment]
Ask twice for the entry of the email address of the PayPal account in order to avoid any error.

**Comment by Yariya** [comment]
noted

**Comment by nestyxx** [comment]
It would be nice to be able to keep the automatic transfer option when we arrive at an exact value and in addition, a transfer on a fixed date. Example: >50$ & 1st of the month

**Comment by nestyxx** [comment]
Display a notification when creating the transfer order on the PayPal account 
Alexandre
--
Payment created as on 2022-03-18 via paypal.com
Sorry. This is already the case but on the next notification.

**Comment by Yariya** [comment]
More suggestions are welcome :)
