### ISSUE TITLE
Doesn't receive hourly notifications

### ISSUE THREAD

**Issue by Izanagi52** [Yariya/EarnApp-Earning-Monitor#43]
Hi,
Since version 2.2.0.2, I don't receive the hourly update notifications.
The app start, send the test notification successfully and nothing else is send.

![Screenshot_2022-03-06-11-21-18-636_com sonelli juicessh~4](https://user-images.githubusercontent.com/21294450/157484285-15053fb9-8b0a-42ff-b08e-d9d8e07f6d32.jpg)

![Screenshot_2022-03-06-11-31-50-110_com discord~3](https://user-images.githubusercontent.com/21294450/156919388-a1adcbff-a9ba-46f9-929e-4437ed5c905c.jpg)

Note : I use the ARM64 docker version on a RPi4 on Ubuntu desktop 21.10, with the default docker-compose file.

**Comment by fazalfarhan01** [comment]
Hi @Izanagi52 I am having similar issues as well. 
Will work on it asap.

**Comment by Yariya** [comment]
Hey trying to look into it today.

**Comment by Yariya** [comment]
Try this without delay and let me know. This should set the delay to default.
```
docker run -d --restart always --name earnapp-monitor \
-e AUTH=YOUR_AUTH_COOKIE_HERE \
-e WEBHOOK_URL=YOUR_WEBHOOK_URL_HERE \
-e AUTOMATIC_REDEEM=0
fazalfarhan01/earnapp-earning-monitor:python-latest
```

**Comment by Izanagi52** [comment]
It seems to works.
I have receive all notification since this (at 10 minute of each hours).
Thanks !

**Comment by Izanagi52** [comment]
I just notice that percentage aren't correctly displayed

![IMG_20220309_171832](https://user-images.githubusercontent.com/21294450/157485215-690335eb-39da-40ae-86b7-051afd28dfd9.jpg)

**Comment by Yariya** [comment]
wait till next update. The values to calculate the percentage don't come from the moon ^^
Calculating the procentage +/- since the last update

**Comment by fazalfarhan01** [comment]
> wait till next update. The values to calculate the percentage don't come from the moon ^^
> Calculating the procentage +/- since the last update

Lol

Anyways.. I tested on my side a few mins ago. Turns out the containers glitched out coz of a network error and sent multiple requests to GitHub to check for updates.. got rate limited and thus the malfunction.

Everything works as expected. Good work on the update @Yariya

**Comment by fazalfarhan01** [comment]
@Izanagi52 closing the issue. Reopen it if you have any related bugs.
