### ISSUE TITLE
earnapp.py error

### ISSUE THREAD

**Issue by nestyxx** [Yariya/EarnApp-Earning-Monitor#49]
line 234
![Capture d’écran 2022-04-12 221146](https://user-images.githubusercontent.com/33231749/163045488-56475f3f-4898-4278-b0bc-5c08da895e91.jpg)

**Comment by nestyxx** [comment]
Errors present after these update
![Capture d’écran 2022-04-14 001312](https://user-images.githubusercontent.com/33231749/163278945-86534340-63dc-49ce-8e94-c27532f8f401.jpg)

**Comment by fazalfarhan01** [comment]
> line 234
> ![Capture d’écran 2022-04-12 221146](https://user-images.githubusercontent.com/33231749/163045488-56475f3f-4898-4278-b0bc-5c08da895e91.jpg)
> 

Looks like your machine isn't able to send a request, or the servers isn't even responding. May be a rate limit thing. Try on a different machine.

**Comment by nestyxx** [comment]
I have just carried out the test after updating the Kaspersky security profiles and on a second ISP. Same result on both machines...

**Comment by eraters** [comment]
@fazalfarhan01 I've found the issue. There needs to be an 'f' before the string in `earnapp.py` line 235, and the error, when the content is shown, is as follows.

pyEarnapp.errors.UnKnownError: Failed to get device statuses. Status code: 400 Response: b'Missing CSRF token'

**Comment by linax101** [comment]
+1 This is impacting me as well, any idea on when the fix will be released @fazalfarhan01 @Yariya  ?

**Comment by fazalfarhan01** [comment]
@eraters thanks for working out the fix. 
@linax101 expect a new update release in another day. (I have been busy, sry)

**Comment by NotTheTube** [comment]
Having the same issue here, I have been using EarnApp for a while but haven't been checking my dashboard, so I just wanted something to remind me of how much I have instead having to refresh to see my earnings. But when trying to but it in my server it doesn't work. Hopefully this can get resolved!

**Comment by eraters** [comment]
Despite the "f" being added, it still does need that CSRF token.
