### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by Megalaoofania** [Yariya/EarnApp-Earning-Monitor#50]
![image](https://user-images.githubusercontent.com/92765223/164039176-23ed2e20-f580-4386-8b26-974da757b9ca.png)
There was an error that happened after installing the new updates. I don't know if this an error with my account or a new error caused with the new code.
I am running Windows 11 Dev Channel.

**Comment by fazalfarhan01** [comment]
Hi @Megalaoofania 
That's an error due to changes in the API. It's a work in progress.

**Comment by Megalaoofania** [comment]
Thanks for letting me know.

**Comment by linax101** [comment]
At this point the app can no longer be used. I started using an older version that doesn't include the device status and that still works.

**Comment by Megalaoofania** [comment]
> At this point the app can no longer be used. I started using an older version that doesn't include the device status and that still works.

I've actually been doing that too and it works then so I'll just wait for the next version to come out before updating.

**Comment by Megalaoofania** [comment]
No longer an issue.
