### ISSUE TITLE
connection closed

### ISSUE THREAD

**Issue by MrAuronTV** [Yariya/EarnApp-Earning-Monitor#52]
Hello

when i'm used my oauth-token-refresh , i've got this error

![image](https://user-images.githubusercontent.com/18170197/164772663-64b7025f-d4ce-471f-b9b6-96d7c41ee0d1.png)

i try to change oauth token but i have this same issue.

Thanks

**Comment by MrAuronTV** [comment]
same with 2.2.0.3 :/

**Comment by Yariya** [comment]
Hello, what device are you using?

**Comment by Yariya** [comment]
Can you try running it without docker? Git clone and run

**Comment by MrAuronTV** [comment]
it seems to be okay, it's connecting on its own
