### ISSUE TITLE
Works on Raspberry Pi ?

### ISSUE THREAD

**Issue by gurkentopf** [Yariya/EarnApp-Earning-Monitor#56]
Hi! Thanks for this. It runs on the computer and Python. Now I don't want to leave the computer on all the time. I have two RaspberryPi in continuous operation. And wanted to ask if it is possible to run the whole thing there? If yes, how do I do that? Thank you for your time.

**Comment by Yariya** [comment]
Hello, yes this is possible via tools such as `screen`.
Simply install screen on Debian based systems via apt `apt install screen`. Most of the times its preinstalled.
If the download doesn't succeed try updating apt first `apt update`.
Run the script: `screen python3 app/main.py` after that you can close your terminal and it will run in the background.
